const packs={
 ar:{settings:'الإعدادات',settingsHint:'اضغط على أي خيار لتعديله',backHome:'الرجوع إلى الصفحة الرئيسية',appLanguage:'لغة التطبيق',chooseLanguage:'اختيار لغة الواجهة',deviceLanguage:'لغة الجهاز',prayerTimes:'مواقيت الصلاة',prayerHint:'مواقيت اليوم حسب موقعك الحالي',arabicCalendar:'التقويم العربي',gregorianCalendar:'التقويم الميلادي',updates:'تحديثات الأفق',checkUpdate:'البحث عن تحديث',checking:'جاري البحث…',alertSettings:'إعدادات التنبيهات',imsakAlert:'تنبيه الإمساك',iftarAlert:'تنبيه الإفطار',prayerAlerts:'تنبيهات الصلوات',adhanSound:'صوت التنبيه والأذان',chooseAdhan:'اختر صوت الأذان',city:'اختيار المدينة يدويًا',showCities:'عرض المدن',closeCities:'إغلاق قائمة المدن',calculation:'طريقة حساب مواقيت الصلاة',privacy:'سياسة الخصوصية',copyright:'حقوق الطبع والنشر والتوزيع',today:'اليوم',previousMonth:'الشهر السابق',nextMonth:'الشهر القادم'},
 'en-US':{settings:'Settings',settingsHint:'Tap an option to change it',backHome:'Back to Home',appLanguage:'App language',chooseLanguage:'Choose interface language',deviceLanguage:'Device language',prayerTimes:'Prayer Times',prayerHint:'Today’s times for your current location',arabicCalendar:'Arabic Calendar',gregorianCalendar:'Gregorian Calendar',updates:'AlOfoK Updates',checkUpdate:'Check for Updates',checking:'Checking…',alertSettings:'Notification Settings',imsakAlert:'Imsak Alert',iftarAlert:'Iftar Alert',prayerAlerts:'Prayer Alerts',adhanSound:'Alert and Adhan Sound',chooseAdhan:'Choose an Adhan sound',city:'Choose City Manually',showCities:'Show Cities',closeCities:'Close City List',calculation:'Prayer Time Calculation Method',privacy:'Privacy Policy',copyright:'Copyright and Distribution',today:'Today',previousMonth:'Previous Month',nextMonth:'Next Month'},
 'en-GB':{settings:'Settings',settingsHint:'Tap an option to change it',backHome:'Back to Home',appLanguage:'App language',chooseLanguage:'Choose interface language',deviceLanguage:'Device language',prayerTimes:'Prayer Times',prayerHint:'Today’s times for your current location',arabicCalendar:'Arabic Calendar',gregorianCalendar:'Gregorian Calendar',updates:'AlOfoK Updates',checkUpdate:'Check for Updates',checking:'Checking…',alertSettings:'Notification Settings',imsakAlert:'Imsak Alert',iftarAlert:'Iftar Alert',prayerAlerts:'Prayer Alerts',adhanSound:'Alert and Adhan Sound',chooseAdhan:'Choose an Adhan sound',city:'Choose City Manually',showCities:'Show Cities',closeCities:'Close City List',calculation:'Prayer Time Calculation Method',privacy:'Privacy Policy',copyright:'Copyright and Distribution',today:'Today',previousMonth:'Previous Month',nextMonth:'Next Month'},
 'en-AU':{settings:'Settings',settingsHint:'Tap an option to change it',backHome:'Back to Home',appLanguage:'App language',chooseLanguage:'Choose interface language',deviceLanguage:'Device language',prayerTimes:'Prayer Times',prayerHint:'Today’s times for your current location',arabicCalendar:'Arabic Calendar',gregorianCalendar:'Gregorian Calendar',updates:'AlOfoK Updates',checkUpdate:'Check for Updates',checking:'Checking…',alertSettings:'Notification Settings',imsakAlert:'Imsak Alert',iftarAlert:'Iftar Alert',prayerAlerts:'Prayer Alerts',adhanSound:'Alert and Adhan Sound',chooseAdhan:'Choose an Adhan sound',city:'Choose City Manually',showCities:'Show Cities',closeCities:'Close City List',calculation:'Prayer Time Calculation Method',privacy:'Privacy Policy',copyright:'Copyright and Distribution',today:'Today',previousMonth:'Previous Month',nextMonth:'Next Month'},
 tr:{settings:'Ayarlar',settingsHint:'Değiştirmek için bir seçeneğe dokunun',backHome:'Ana sayfaya dön',appLanguage:'Uygulama dili',chooseLanguage:'Arayüz dilini seçin',deviceLanguage:'Cihaz dili',prayerTimes:'Namaz Vakitleri',prayerHint:'Mevcut konumunuz için bugünkü vakitler',arabicCalendar:'Arap Takvimi',gregorianCalendar:'Miladi Takvim',updates:'AlOfoK Güncellemeleri',checkUpdate:'Güncellemeleri Kontrol Et',checking:'Kontrol ediliyor…',alertSettings:'Bildirim Ayarları',imsakAlert:'İmsak Uyarısı',iftarAlert:'İftar Uyarısı',prayerAlerts:'Namaz Uyarıları',adhanSound:'Uyarı ve Ezan Sesi',chooseAdhan:'Ezan sesi seçin',city:'Şehri Elle Seç',showCities:'Şehirleri Göster',closeCities:'Şehir Listesini Kapat',calculation:'Namaz Vakti Hesaplama Yöntemi',privacy:'Gizlilik Politikası',copyright:'Telif ve Dağıtım',today:'Bugün',previousMonth:'Önceki Ay',nextMonth:'Sonraki Ay'},
 fr:{settings:'Paramètres',settingsHint:'Touchez une option pour la modifier',backHome:'Retour à l’accueil',appLanguage:'Langue de l’application',chooseLanguage:'Choisir la langue de l’interface',deviceLanguage:'Langue de l’appareil',prayerTimes:'Horaires de prière',prayerHint:'Horaires du jour selon votre position',arabicCalendar:'Calendrier arabe',gregorianCalendar:'Calendrier grégorien',updates:'Mises à jour AlOfoK',checkUpdate:'Rechercher des mises à jour',checking:'Recherche…',alertSettings:'Paramètres des notifications',imsakAlert:'Alerte Imsak',iftarAlert:'Alerte Iftar',prayerAlerts:'Alertes de prière',adhanSound:'Son d’alerte et de l’adhan',chooseAdhan:'Choisir un son d’adhan',city:'Choisir la ville manuellement',showCities:'Afficher les villes',closeCities:'Fermer la liste',calculation:'Méthode de calcul des prières',privacy:'Politique de confidentialité',copyright:'Droits d’auteur et distribution',today:'Aujourd’hui',previousMonth:'Mois précédent',nextMonth:'Mois suivant'},
 de:{settings:'Einstellungen',settingsHint:'Tippen Sie auf eine Option, um sie zu ändern',backHome:'Zurück zur Startseite',appLanguage:'App-Sprache',chooseLanguage:'Sprache der Benutzeroberfläche wählen',deviceLanguage:'Gerätesprache',prayerTimes:'Gebetszeiten',prayerHint:'Heutige Zeiten für Ihren Standort',arabicCalendar:'Arabischer Kalender',gregorianCalendar:'Gregorianischer Kalender',updates:'AlOfoK-Aktualisierungen',checkUpdate:'Nach Updates suchen',checking:'Suche…',alertSettings:'Benachrichtigungseinstellungen',imsakAlert:'Imsak-Erinnerung',iftarAlert:'Iftar-Erinnerung',prayerAlerts:'Gebetserinnerungen',adhanSound:'Benachrichtigungs- und Adhan-Ton',chooseAdhan:'Adhan-Ton auswählen',city:'Stadt manuell auswählen',showCities:'Städte anzeigen',closeCities:'Städteliste schließen',calculation:'Berechnungsmethode der Gebetszeiten',privacy:'Datenschutzrichtlinie',copyright:'Urheberrecht und Verteilung',today:'Heute',previousMonth:'Vorheriger Monat',nextMonth:'Nächster Monat'},
 ru:{settings:'Настройки',settingsHint:'Нажмите на параметр, чтобы изменить его',backHome:'На главную',appLanguage:'Язык приложения',chooseLanguage:'Выберите язык интерфейса',deviceLanguage:'Язык устройства',prayerTimes:'Время молитв',prayerHint:'Расписание на сегодня для вашего местоположения',arabicCalendar:'Арабский календарь',gregorianCalendar:'Григорианский календарь',updates:'Обновления AlOfoK',checkUpdate:'Проверить обновления',checking:'Проверка…',alertSettings:'Настройки уведомлений',imsakAlert:'Уведомление об имсаке',iftarAlert:'Уведомление об ифтаре',prayerAlerts:'Уведомления о молитвах',adhanSound:'Звук уведомления и азана',chooseAdhan:'Выберите звук азана',city:'Выбрать город вручную',showCities:'Показать города',closeCities:'Закрыть список городов',calculation:'Метод расчёта времени молитв',privacy:'Политика конфиденциальности',copyright:'Авторские права и распространение',today:'Сегодня',previousMonth:'Предыдущий месяц',nextMonth:'Следующий месяц'}
};
export function makeTranslator(language){
 const selected=language==='system'?'ar':language;
 const pack=packs[selected]||packs[selected.split('-')[0]]||packs['en-US'];
 return (key)=>pack[key]??packs.ar[key]??key;
}
export const translatedLocales=Object.keys(packs);
