import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Platform,Pressable,ScrollView,StyleSheet,Switch,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Notifications from 'expo-notifications';

const NAVY='#06182B',CARD='rgba(17,34,52,0.92)',LINE='rgba(255,255,255,0.15)',WHITE='#F7F8FB',GOLD='#F4C45D',MUTED='#B9C4D1';
const KEYS={morning:'alofok_v3_adhkar_morning_enabled',evening:'alofok_v3_adhkar_evening_enabled',morningAlert:'alofok_v3_adhkar_morning_alert',eveningAlert:'alofok_v3_adhkar_evening_alert',morningDone:'alofok_v3_adhkar_morning_done',eveningDone:'alofok_v3_adhkar_evening_done'};

export const MORNING_ADHKAR=[
 {title:'آية الكرسي',count:'مرة واحدة',text:'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ.'},
 {title:'سورة الإخلاص',count:'3 مرات',text:'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ.'},
 {title:'سورة الفلق',count:'3 مرات',text:'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ ۝ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ.'},
 {title:'سورة الناس',count:'3 مرات',text:'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ.'},
 {title:'ذكر الصباح',count:'مرة واحدة',text:'أصبحنا وأصبح الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير. رب أسألك خير ما في هذا اليوم وخير ما بعده، وأعوذ بك من شر ما في هذا اليوم وشر ما بعده.'},
 {title:'اللهم بك أصبحنا',count:'مرة واحدة',text:'اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور.'},
 {title:'رضيت بالله',count:'3 مرات',text:'رضيت بالله ربًّا، وبالإسلام دينًا، وبمحمد ﷺ نبيًّا.'},
 {title:'بسم الله الذي لا يضر',count:'3 مرات',text:'بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم.'},
 {title:'سيد الاستغفار',count:'مرة واحدة',text:'اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شر ما صنعت، أبوء لك بنعمتك علي، وأبوء بذنبي، فاغفر لي فإنه لا يغفر الذنوب إلا أنت.'},
 {title:'التسبيح',count:'100 مرة',text:'سبحان الله وبحمده.'}
];
export const EVENING_ADHKAR=[...MORNING_ADHKAR.slice(0,4),{title:'ذكر المساء',count:'مرة واحدة',text:'أمسينا وأمسى الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير. رب أسألك خير ما في هذه الليلة وخير ما بعدها، وأعوذ بك من شر ما في هذه الليلة وشر ما بعدها.'},{title:'اللهم بك أمسينا',count:'مرة واحدة',text:'اللهم بك أمسينا وبك أصبحنا وبك نحيا وبك نموت وإليك المصير.'},...MORNING_ADHKAR.slice(6)];

function zoneParts(date,timeZone){try{const p=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);const v=Object.fromEntries(p.map(x=>[x.type,x.value]));return {year:+v.year,month:+v.month,day:+v.day,hour:+v.hour,minute:+v.minute};}catch(_){return {year:date.getFullYear(),month:date.getMonth()+1,day:date.getDate(),hour:date.getHours(),minute:date.getMinutes()};}}
function dayKey(date,timeZone){const p=zoneParts(date,timeZone);return `${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}`;}
function atLocalHour(base,timeZone,hour,minute=0){const p=zoneParts(base,timeZone);const wall=Date.UTC(p.year,p.month-1,p.day,hour,minute,0);let g=new Date(wall);for(let i=0;i<2;i++){const q=zoneParts(g,timeZone);const represented=Date.UTC(q.year,q.month-1,q.day,q.hour,q.minute,0);g=new Date(wall-(represented-g.getTime()));}return g;}
function morningWindow(now,fajr,timeZone){if(!(fajr instanceof Date)||Number.isNaN(fajr.getTime()))return false;const p=zoneParts(now,timeZone);return now.getTime()>=fajr.getTime()&&(p.hour*60+p.minute)<600;}
function eveningWindow(now,timeZone){const p=zoneParts(now,timeZone),m=p.hour*60+p.minute;return m>=1260&&m<1440;}
async function permission(){const p=await Notifications.getPermissionsAsync();if(p.status==='granted')return true;return (await Notifications.requestPermissionsAsync()).status==='granted';}

export function useAdhkar({now,fajrDate,timeZone='Asia/Baghdad',language='ar'}){
 const [morningEnabled,setMorningEnabledState]=useState(true),[eveningEnabled,setEveningEnabledState]=useState(true);
 const [morningAlert,setMorningAlertState]=useState(false),[eveningAlert,setEveningAlertState]=useState(false);
 const [morningDone,setMorningDone]=useState(''),[eveningDone,setEveningDone]=useState(''),[openedKind,setOpenedKind]=useState(null),[ready,setReady]=useState(false);
 const today=dayKey(now,timeZone);
 useEffect(()=>{Promise.all(Object.values(KEYS).map(k=>AsyncStorage.getItem(k))).then(([m,e,ma,ea,md,ed])=>{setMorningEnabledState(m!=='0');setEveningEnabledState(e!=='0');setMorningAlertState(ma==='1');setEveningAlertState(ea==='1');setMorningDone(md||'');setEveningDone(ed||'');setReady(true);}).catch(()=>setReady(true));},[]);
 useEffect(()=>{const sub=Notifications.addNotificationResponseReceivedListener(r=>{const d=r?.notification?.request?.content?.data||{};if(d.kind==='alofok-v3-adhkar'&&(d.period==='morning'||d.period==='evening'))setOpenedKind(d.period);});return()=>sub.remove();},[]);
 const setMorningEnabled=useCallback(async v=>{setMorningEnabledState(!!v);await AsyncStorage.setItem(KEYS.morning,v?'1':'0').catch(()=>{});},[]);
 const setEveningEnabled=useCallback(async v=>{setEveningEnabledState(!!v);await AsyncStorage.setItem(KEYS.evening,v?'1':'0').catch(()=>{});},[]);
 const setMorningAlert=useCallback(async v=>{if(v&&!(await permission()))return false;setMorningAlertState(!!v);await AsyncStorage.setItem(KEYS.morningAlert,v?'1':'0').catch(()=>{});return true;},[]);
 const setEveningAlert=useCallback(async v=>{if(v&&!(await permission()))return false;setEveningAlertState(!!v);await AsyncStorage.setItem(KEYS.eveningAlert,v?'1':'0').catch(()=>{});return true;},[]);
 const markComplete=useCallback(async kind=>{const key=dayKey(new Date(),timeZone);if(kind==='morning'){setMorningDone(key);await AsyncStorage.setItem(KEYS.morningDone,key).catch(()=>{});}else{setEveningDone(key);await AsyncStorage.setItem(KEYS.eveningDone,key).catch(()=>{});}},[timeZone]);
 const visibleKind=useMemo(()=>{if(!ready)return null;if(morningEnabled&&morningDone!==today&&morningWindow(now,fajrDate,timeZone))return 'morning';if(eveningEnabled&&eveningDone!==today&&eveningWindow(now,timeZone))return 'evening';return null;},[ready,morningEnabled,eveningEnabled,morningDone,eveningDone,today,now,fajrDate,timeZone]);
 const clearOpened=useCallback(()=>setOpenedKind(null),[]);
 const schedule=useCallback(async()=>{try{const old=await Notifications.getAllScheduledNotificationsAsync();for(const n of old)if(n.content?.data?.kind==='alofok-v3-adhkar')await Notifications.cancelScheduledNotificationAsync(n.identifier);if(!morningAlert&&!eveningAlert)return;const p=await Notifications.getPermissionsAsync();if(p.status!=='granted')return;const channelId='alofok-v3-adhkar';if(Platform.OS==='android')await Notifications.setNotificationChannelAsync(channelId,{name:'Al-Ufuq — أذكار',importance:Notifications.AndroidImportance.DEFAULT,sound:'default'});const current=new Date(),key=dayKey(current,timeZone);const one=async(period,date)=>{if(!(date instanceof Date)||date.getTime()<=current.getTime())return;const ar=String(language).startsWith('ar'),morning=period==='morning';await Notifications.scheduleNotificationAsync({content:{title:ar?(morning?'أذكار الصباح':'أذكار المساء'):(morning?'Morning adhkar':'Evening adhkar'),body:ar?(morning?'حان وقت أذكار الصباح.':'حان وقت أذكار المساء.'):(morning?'It is time for morning adhkar.':'It is time for evening adhkar.'),sound:'default',data:{kind:'alofok-v3-adhkar',period}},trigger:{type:Notifications.SchedulableTriggerInputTypes.DATE,date,channelId:Platform.OS==='android'?channelId:undefined}});};if(morningEnabled&&morningAlert&&morningDone!==key&&fajrDate instanceof Date)await one('morning',new Date(fajrDate.getTime()+60000));if(eveningEnabled&&eveningAlert&&eveningDone!==key)await one('evening',atLocalHour(current,timeZone,21,0));}catch(_){}},[morningEnabled,eveningEnabled,morningAlert,eveningAlert,morningDone,eveningDone,fajrDate,timeZone,language]);
 return {morningEnabled,eveningEnabled,morningAlert,eveningAlert,setMorningEnabled,setEveningEnabled,setMorningAlert,setEveningAlert,visibleKind,markComplete,schedule,openedKind,clearOpened};
}

export function AdhkarHomeCard({kind,rtl,onPress}){const morning=kind==='morning';return <Pressable onPress={onPress} style={s.homeCard}><Text style={s.homeIcon}>{morning?'☀':'☾'}</Text><View style={{flex:1}}><Text style={[s.homeTitle,{textAlign:rtl?'right':'left'}]}>{rtl?(morning?'أذكار الصباح':'أذكار المساء'):(morning?'Morning adhkar':'Evening adhkar')}</Text><Text style={[s.homeHint,{textAlign:rtl?'right':'left'}]}>{rtl?(morning?'متاحة حتى 10:00 صباحًا':'متاحة حتى 12:00 منتصف الليل'):(morning?'Available until 10:00 AM':'Available until midnight')}</Text></View><Text style={s.chevron}>{rtl?'‹':'›'}</Text></Pressable>;}

export function AdhkarSettings({rtl,adhkar}){const Row=({title,hint,value,onChange})=><View style={s.settingCard}><View style={[s.settingRow,{flexDirection:rtl?'row-reverse':'row'}]}><View style={{flex:1}}><Text style={[s.settingTitle,{textAlign:rtl?'right':'left'}]}>{title}</Text><Text style={[s.settingHint,{textAlign:rtl?'right':'left'}]}>{hint}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{false:'#38495B',true:'#A87B28'}} thumbColor={value?GOLD:'#E8EDF2'}/></View></View>;return <View style={s.settingsWrap}><Row title={rtl?'أذكار الصباح':'Morning adhkar'} hint={rtl?'بعد الفجر حتى 10:00 صباحًا':'After Fajr until 10:00 AM'} value={adhkar.morningEnabled} onChange={adhkar.setMorningEnabled}/><Row title={rtl?'منبّه أذكار الصباح':'Morning adhkar alert'} hint={rtl?'تنبيه بعد أذان الفجر':'Alert after Fajr'} value={adhkar.morningAlert} onChange={adhkar.setMorningAlert}/><Row title={rtl?'أذكار المساء':'Evening adhkar'} hint={rtl?'من 9:00 مساءً حتى منتصف الليل':'9:00 PM until midnight'} value={adhkar.eveningEnabled} onChange={adhkar.setEveningEnabled}/><Row title={rtl?'منبّه أذكار المساء':'Evening adhkar alert'} hint={rtl?'تنبيه الساعة 9:00 مساءً':'Alert at 9:00 PM'} value={adhkar.eveningAlert} onChange={adhkar.setEveningAlert}/></View>;}

export function AdhkarScreen({kind,rtl,onBack,onComplete}){const items=kind==='morning'?MORNING_ADHKAR:EVENING_ADHKAR;const finish=async()=>{await onComplete(kind);onBack();};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={[s.header,{flexDirection:rtl?'row-reverse':'row'}]}><Pressable onPress={onBack} style={s.back}><Text style={s.backText}>{rtl?'›':'‹'}</Text></Pressable><Text style={[s.title,{textAlign:rtl?'right':'left'}]}>{rtl?(kind==='morning'?'أذكار الصباح':'أذكار المساء'):(kind==='morning'?'Morning adhkar':'Evening adhkar')}</Text><View style={{width:44}}/></View>{items.map((x,i)=><View key={i} style={s.dhikrCard}><View style={[s.dhikrTop,{flexDirection:rtl?'row-reverse':'row'}]}><Text style={s.dhikrTitle}>{x.title}</Text><Text style={s.count}>{x.count}</Text></View><Text selectable style={s.dhikrText}>{x.text}</Text></View>)}<Pressable onPress={finish} style={s.doneButton}><Text style={s.doneText}>{rtl?'تمت القراءة — إخفاء':'Finished — hide'}</Text></Pressable></ScrollView></SafeAreaView>;}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:NAVY},content:{padding:18,paddingBottom:50},header:{height:60,alignItems:'center',justifyContent:'space-between'},back:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(4,20,37,.58)',borderWidth:1,borderColor:LINE},backText:{color:WHITE,fontSize:30},title:{color:WHITE,fontSize:24,fontWeight:'900',flex:1,marginHorizontal:12},homeCard:{marginTop:12,minHeight:72,borderRadius:16,borderWidth:1,borderColor:'rgba(244,196,93,.55)',backgroundColor:'rgba(7,23,41,.88)',paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:12},homeIcon:{color:GOLD,fontSize:24},homeTitle:{color:GOLD,fontSize:17,fontWeight:'900'},homeHint:{color:MUTED,fontSize:11,marginTop:4},chevron:{color:WHITE,fontSize:26},settingsWrap:{gap:10,marginTop:10},settingCard:{backgroundColor:CARD,borderRadius:16,borderWidth:1,borderColor:LINE,padding:14},settingRow:{alignItems:'center',gap:12},settingTitle:{color:WHITE,fontSize:15,fontWeight:'800'},settingHint:{color:MUTED,fontSize:11,marginTop:4},dhikrCard:{backgroundColor:CARD,borderRadius:18,borderWidth:1,borderColor:LINE,padding:15,marginTop:12},dhikrTop:{alignItems:'center',justifyContent:'space-between',gap:8},dhikrTitle:{color:GOLD,fontSize:16,fontWeight:'900',flex:1,textAlign:'right'},count:{color:MUTED,fontSize:11},dhikrText:{color:WHITE,fontSize:18,lineHeight:34,textAlign:'right',writingDirection:'rtl',marginTop:12},doneButton:{backgroundColor:GOLD,borderRadius:15,paddingVertical:15,alignItems:'center',marginTop:18},doneText:{color:NAVY,fontSize:15,fontWeight:'900'}});
