import {makeTranslator} from '../i18n/translations';
import {localeTag,isRtlLocale} from '../i18n/locales';

const en={
 appName:'Alufuq',tagline:'The fixed Arabic calendar',menu:'Menu',home:'Home',settings:'Settings',checkUpdate:'Check for Updates',subscription:'Subscription',support:'Support',advertise:'Advertise with us',languages:'Languages',about:'About',privacy:'Privacy',copyright:'Copyright & IP',authenticity:'Verify authenticity',close:'Close',back:'Back',gps:'GPS',locating:'Locating…',locationUnavailable:'Location unavailable',locationDenied:'Location permission denied',accuracy:'Accuracy',
 prayerTimes:'Prayer Times',showAll:'Show all',fajr:'Fajr',sunrise:'Sunrise',dhuhr:'Dhuhr',asr:'Asr',maghrib:'Maghrib',isha:'Isha',hijriCalendar:'Alufuq Calendar',gregorianCalendar:'Gregorian Calendar',previousMonth:'Previous month',nextMonth:'Next month',today:'Today',
 adhanTitle:'Adhan',adhanHint:'Choose your preferred Adhan',previewSound:'Preview sound',adhanVolume:'Adhan volume',licensed:'Licensed',audioError:'This audio could not be played. Please choose another sound.',audioReady:'Ready to play',source:'Source',license:'License',
 themes:'Themes & Backgrounds',themesHint:'Choose what inspires you every day',seasons:'Seasons',atmospheres:'Atmospheres',weekdays:'Weekdays',months:'Arabic months',special:'Special',themeFixed:'Mosque minaret',automatic:'Automatic',spring:'Spring',summer:'Summer',autumn:'Autumn',winter:'Winter',dawn:'Dawn',morning:'Morning',day:'Daytime',sunset:'Sunset',night:'Night',
 sunday:'Sunday',monday:'Monday',tuesday:'Tuesday',wednesday:'Wednesday',thursday:'Thursday',friday:'Friday',saturday:'Saturday',muharram:'Muharram',safar:'Safar',rabi1:'Rabi I',rabi2:'Rabi II',jumada1:'Jumada I',jumada2:'Jumada II',rajab:'Rajab',shaban:"Sha'ban",ramadan:'Ramadan',shawwal:'Shawwal',dhulqida:'Dhu al-Qidah',dhulhijja:'Dhu al-Hijjah',newYear:'New Year',equinox:'Equinox',solarEclipse:'Solar eclipse',lunarEclipse:'Lunar eclipse',summerSolstice:'Summer solstice',winterSolstice:'Winter solstice',
 chooseExperience:'Choose your Alufuq experience',free:'Free',plus:'Alufuq Plus',allEssentials:'All essentials',plusExperience:'A richer and more inspiring experience',subscribeNow:'Subscribe now',currentPlan:'Current plan',freePrayer:'Prayer times',freeCalendars:'Alufuq and Gregorian calendars',freeThemes:'Limited themes',freeCore:'Core features',plusAllFree:'Everything in Free',plusThemes:'All exclusive themes',plusAdhan:'Additional licensed Adhan sounds',plusSeasons:'Automatic seasonal and daily themes',plusSupport:'Supports continued development',
 aboutTitle:'About Alufuq',researchDisclaimer:'This app is not a religious authority; it is a scientific/research calendar project.',researchBody:'Alufuq explores a seasonal Arabic calendar model, using astronomical conjunction as the computational month-start layer while keeping local crescent visibility as a separate layer. In the research model, a leap year can contain 13 months and the added month is called the Nasi’ month. Prayer times are calculated locally from date, coordinates and the selected calculation standard.',
 languageTitle:'Interface language',languageHint:'All interface labels, dates and screen direction follow the selected language.',select:'Select',selected:'Selected',plusOnly:'Plus only',tryAgain:'Try again',refresh:'Refresh',location:'Location',savedLocation:'Saved location',manualCity:'Choose city manually',research:'Research',calendar:'Calendar',notifications:'Notifications',notAvailable:'Not available',permissionRequired:'Permission required'
};

const ar={
 appName:'الأفق',tagline:'التقويم العربي الثابت',menu:'القائمة',home:'الرئيسية',settings:'الإعدادات',checkUpdate:'بحث عن تحديث',subscription:'الاشتراك',support:'الدعم',advertise:'أعلن معنا',languages:'اللغات',about:'حول',privacy:'الخصوصية',copyright:'حقوق الطبع والنشر',authenticity:'التحقق من الأصالة',close:'إغلاق',back:'رجوع',gps:'GPS',locating:'جاري تحديد الموقع…',locationUnavailable:'تعذر تحديد الموقع',locationDenied:'لم يُسمح بالوصول إلى الموقع',accuracy:'الدقة',
 prayerTimes:'مواقيت الصلاة',showAll:'عرض الكل',fajr:'الفجر',sunrise:'الشروق',dhuhr:'الظهر',asr:'العصر',maghrib:'المغرب',isha:'العشاء',hijriCalendar:'التقويم الهجري',gregorianCalendar:'التقويم الميلادي',previousMonth:'الشهر السابق',nextMonth:'الشهر القادم',today:'اليوم',
 adhanTitle:'تطبيق الأذان',adhanHint:'اختر صوت الأذان المفضل لديك',previewSound:'معاينة الصوت',adhanVolume:'مستوى صوت الأذان',licensed:'مرخص',audioError:'تعذر تشغيل هذا الصوت. اختر صوتًا آخر.',audioReady:'جاهز للتشغيل',source:'المصدر',license:'الترخيص',
 themes:'الثيمات والخلفيات',themesHint:'اختر ما يلهمك كل يوم',seasons:'المواسم',atmospheres:'الأجواء',weekdays:'أيام الأسبوع',months:'الأشهر العربية',special:'مناسبات خاصة',themeFixed:'منارة الجامع',automatic:'تلقائي',spring:'الربيع',summer:'الصيف',autumn:'الخريف',winter:'الشتاء',dawn:'الفجر',morning:'الصباح',day:'النهار',sunset:'الغروب',night:'الليل',
 sunday:'الأحد',monday:'الاثنين',tuesday:'الثلاثاء',wednesday:'الأربعاء',thursday:'الخميس',friday:'الجمعة',saturday:'السبت',muharram:'محرم',safar:'صفر',rabi1:'ربيع الأول',rabi2:'ربيع الآخر',jumada1:'جمادى الأولى',jumada2:'جمادى الآخرة',rajab:'رجب',shaban:'شعبان',ramadan:'رمضان',shawwal:'شوال',dhulqida:'ذو القعدة',dhulhijja:'ذو الحجة',newYear:'رأس السنة',equinox:'الاعتدال',solarEclipse:'كسوف الشمس',lunarEclipse:'خسوف القمر',summerSolstice:'الانقلاب الصيفي',winterSolstice:'الانقلاب الشتوي',
 chooseExperience:'اختر تجربتك مع الأفق',free:'المجاني',plus:'الأفق Plus',allEssentials:'جميع الأساسيات',plusExperience:'تجربة أكثر جمالًا وإلهامًا',subscribeNow:'اشترك الآن',currentPlan:'مستخدم حاليًا',freePrayer:'مواقيت الصلاة',freeCalendars:'التقويم الهجري والميلادي',freeThemes:'عدد محدود من الخلفيات',freeCore:'جميع الميزات الأساسية',plusAllFree:'جميع ميزات النسخة المجانية',plusThemes:'جميع الخلفيات الحصرية',plusAdhan:'أصوات أذان إضافية مرخصة وعالية الجودة',plusSeasons:'ثيمات موسمية ويومية تلقائية',plusSupport:'دعم استمرار تطوير التطبيق',
 aboutTitle:'حول الأفق',researchDisclaimer:'هذا البرنامج ليس دينيًا، وإنما مشروع وبحث علمي في التقويم.',researchBody:'الأفق يدرس نموذجًا للتقويم العربي المرتبط بالمواسم، ويستخدم الاقتران الفلكي كطبقة حسابية لبداية الشهر مع إبقاء الرؤية المحلية للهلال طبقة مستقلة. في النموذج البحثي قد تكون السنة الكبيسة 13 شهرًا، ويسمى الشهر المضاف «شهر النسيء». وتُحسب مواقيت الصلاة محليًا من التاريخ والإحداثيات ومعيار الحساب المختار.',
 languageTitle:'لغة الواجهة',languageHint:'كل عناوين الواجهة والتواريخ واتجاه الشاشة تتبع اللغة المختارة.',select:'اختيار',selected:'محدد',plusOnly:'لبلاس فقط',tryAgain:'حاول مرة أخرى',refresh:'تحديث',location:'الموقع',savedLocation:'الموقع المحفوظ',manualCity:'اختيار المدينة يدويًا',research:'البحث العلمي',calendar:'التقويم',notifications:'التنبيهات',notAvailable:'غير متاح',permissionRequired:'الإذن مطلوب'
};

function withEnglish(overrides){return {...en,...overrides}}

const packs={
 ar,
 en,
 'en-US':en,
 'en-GB':en,
 'en-AU':en,
 fr:withEnglish({settings:'Paramètres',checkUpdate:'Rechercher une mise à jour',subscription:'Abonnement',support:'Soutien',languages:'Langues',about:'À propos',privacy:'Confidentialité',close:'Fermer',back:'Retour',prayerTimes:'Horaires de prière',showAll:'Tout afficher',hijriCalendar:'Calendrier Alufuq',gregorianCalendar:'Calendrier grégorien',adhanTitle:'Adhan',adhanHint:'Choisissez votre Adhan préféré',previewSound:'Aperçu du son',themes:'Thèmes et arrière-plans',themesHint:'Choisissez ce qui vous inspire chaque jour',seasons:'Saisons',atmospheres:'Ambiances',weekdays:'Jours de la semaine',months:'Mois arabes',spring:'Printemps',summer:'Été',autumn:'Automne',winter:'Hiver',dawn:'Aube',morning:'Matin',day:'Jour',sunset:'Coucher du soleil',night:'Nuit',chooseExperience:'Choisissez votre expérience Alufuq',free:'Gratuit',subscribeNow:'S’abonner maintenant',currentPlan:'Forfait actuel',aboutTitle:'À propos d’Alufuq',researchDisclaimer:'Cette application n’est pas une autorité religieuse ; c’est un projet scientifique et de recherche sur le calendrier.',languageTitle:'Langue de l’interface'}),
 es:withEnglish({settings:'Ajustes',checkUpdate:'Buscar actualizaciones',subscription:'Suscripción',support:'Soporte',languages:'Idiomas',about:'Acerca de',privacy:'Privacidad',close:'Cerrar',back:'Atrás',prayerTimes:'Horarios de oración',showAll:'Ver todo',hijriCalendar:'Calendario Alufuq',gregorianCalendar:'Calendario gregoriano',adhanTitle:'Adhan',adhanHint:'Elige tu Adhan preferido',previewSound:'Vista previa del sonido',themes:'Temas y fondos',themesHint:'Elige lo que te inspire cada día',seasons:'Estaciones',atmospheres:'Ambientes',weekdays:'Días de la semana',months:'Meses árabes',spring:'Primavera',summer:'Verano',autumn:'Otoño',winter:'Invierno',dawn:'Amanecer',morning:'Mañana',day:'Día',sunset:'Atardecer',night:'Noche',chooseExperience:'Elige tu experiencia Alufuq',free:'Gratis',subscribeNow:'Suscríbete ahora',currentPlan:'Plan actual',aboutTitle:'Acerca de Alufuq',researchDisclaimer:'Esta aplicación no es una autoridad religiosa; es un proyecto científico y de investigación del calendario.',languageTitle:'Idioma de la interfaz'}),
 de:withEnglish({settings:'Einstellungen',checkUpdate:'Nach Updates suchen',subscription:'Abonnement',support:'Unterstützung',languages:'Sprachen',about:'Über',privacy:'Datenschutz',close:'Schließen',back:'Zurück',prayerTimes:'Gebetszeiten',showAll:'Alle anzeigen',hijriCalendar:'Alufuq-Kalender',gregorianCalendar:'Gregorianischer Kalender',adhanTitle:'Adhan',adhanHint:'Wähle deinen bevorzugten Adhan',previewSound:'Tonvorschau',themes:'Designs & Hintergründe',themesHint:'Wähle, was dich jeden Tag inspiriert',seasons:'Jahreszeiten',atmospheres:'Stimmungen',weekdays:'Wochentage',months:'Arabische Monate',spring:'Frühling',summer:'Sommer',autumn:'Herbst',winter:'Winter',dawn:'Morgendämmerung',morning:'Morgen',day:'Tag',sunset:'Sonnenuntergang',night:'Nacht',chooseExperience:'Wähle dein Alufuq-Erlebnis',free:'Kostenlos',subscribeNow:'Jetzt abonnieren',currentPlan:'Aktueller Plan',aboutTitle:'Über Alufuq',researchDisclaimer:'Diese App ist keine religiöse Autorität; sie ist ein wissenschaftliches Kalender-Forschungsprojekt.',languageTitle:'Oberflächensprache'}),
 tr:withEnglish({settings:'Ayarlar',checkUpdate:'Güncellemeleri kontrol et',subscription:'Abonelik',support:'Destek',languages:'Diller',about:'Hakkında',privacy:'Gizlilik',close:'Kapat',back:'Geri',prayerTimes:'Namaz vakitleri',showAll:'Tümünü göster',hijriCalendar:'Alufuq Takvimi',gregorianCalendar:'Miladi Takvim',adhanTitle:'Ezan',adhanHint:'Tercih ettiğiniz ezanı seçin',previewSound:'Ses önizleme',themes:'Temalar ve arka planlar',themesHint:'Her gün size ilham vereni seçin',seasons:'Mevsimler',atmospheres:'Atmosferler',weekdays:'Haftanın günleri',months:'Arap ayları',spring:'İlkbahar',summer:'Yaz',autumn:'Sonbahar',winter:'Kış',dawn:'Şafak',morning:'Sabah',day:'Gündüz',sunset:'Gün batımı',night:'Gece',chooseExperience:'Alufuq deneyiminizi seçin',free:'Ücretsiz',subscribeNow:'Şimdi abone ol',currentPlan:'Mevcut plan',aboutTitle:'Alufuq Hakkında',researchDisclaimer:'Bu uygulama dini bir otorite değildir; bilimsel bir takvim araştırma projesidir.',languageTitle:'Arayüz dili'}),
 ru:withEnglish({settings:'Настройки',checkUpdate:'Проверить обновления',subscription:'Подписка',support:'Поддержка',languages:'Языки',about:'О приложении',privacy:'Конфиденциальность',close:'Закрыть',back:'Назад',prayerTimes:'Время молитв',showAll:'Показать все',hijriCalendar:'Календарь Alufuq',gregorianCalendar:'Григорианский календарь',adhanTitle:'Азан',adhanHint:'Выберите предпочитаемый азан',previewSound:'Прослушать',themes:'Темы и фоны',themesHint:'Выберите то, что вдохновляет вас каждый день',seasons:'Сезоны',atmospheres:'Атмосферы',weekdays:'Дни недели',months:'Арабские месяцы',spring:'Весна',summer:'Лето',autumn:'Осень',winter:'Зима',dawn:'Рассвет',morning:'Утро',day:'День',sunset:'Закат',night:'Ночь',chooseExperience:'Выберите свой опыт Alufuq',free:'Бесплатно',subscribeNow:'Подписаться',currentPlan:'Текущий план',aboutTitle:'Об Alufuq',researchDisclaimer:'Это приложение не является религиозным авторитетом; это научный исследовательский проект календаря.',languageTitle:'Язык интерфейса'}),
 'zh-CN':withEnglish({settings:'设置',checkUpdate:'检查更新',subscription:'订阅',support:'支持',languages:'语言',about:'关于',privacy:'隐私',close:'关闭',back:'返回',prayerTimes:'礼拜时间',showAll:'查看全部',hijriCalendar:'Alufuq 日历',gregorianCalendar:'公历',adhanTitle:'宣礼',adhanHint:'选择您喜欢的宣礼声',previewSound:'试听',themes:'主题与背景',themesHint:'选择每天给你灵感的画面',seasons:'季节',atmospheres:'氛围',weekdays:'星期',months:'阿拉伯月份',spring:'春季',summer:'夏季',autumn:'秋季',winter:'冬季',dawn:'黎明',morning:'早晨',day:'白天',sunset:'日落',night:'夜晚',chooseExperience:'选择你的 Alufuq 体验',free:'免费',subscribeNow:'立即订阅',currentPlan:'当前方案',aboutTitle:'关于 Alufuq',researchDisclaimer:'本应用不是宗教权威；它是一个科学与研究性质的历法项目。',languageTitle:'界面语言'}),
 'zh-TW':withEnglish({settings:'設定',checkUpdate:'檢查更新',subscription:'訂閱',support:'支援',languages:'語言',about:'關於',privacy:'隱私',close:'關閉',back:'返回',prayerTimes:'禮拜時間',showAll:'查看全部',hijriCalendar:'Alufuq 日曆',gregorianCalendar:'公曆',adhanTitle:'宣禮',adhanHint:'選擇您喜歡的宣禮聲',previewSound:'試聽',themes:'主題與背景',themesHint:'選擇每天給你靈感的畫面',seasons:'季節',atmospheres:'氛圍',weekdays:'星期',months:'阿拉伯月份',spring:'春季',summer:'夏季',autumn:'秋季',winter:'冬季',dawn:'黎明',morning:'早晨',day:'白天',sunset:'日落',night:'夜晚',chooseExperience:'選擇你的 Alufuq 體驗',free:'免費',subscribeNow:'立即訂閱',currentPlan:'目前方案',aboutTitle:'關於 Alufuq',researchDisclaimer:'本應用不是宗教權威；它是一個科學與研究性質的曆法專案。',languageTitle:'介面語言'}),
 fa:withEnglish({settings:'تنظیمات',checkUpdate:'بررسی به‌روزرسانی',subscription:'اشتراک',support:'پشتیبانی',languages:'زبان‌ها',about:'درباره',privacy:'حریم خصوصی',close:'بستن',back:'بازگشت',prayerTimes:'اوقات نماز',showAll:'نمایش همه',hijriCalendar:'تقویم Alufuq',gregorianCalendar:'تقویم میلادی',adhanTitle:'اذان',adhanHint:'صدای اذان دلخواه را انتخاب کنید',previewSound:'پیش‌نمایش صدا',themes:'تم‌ها و پس‌زمینه‌ها',themesHint:'هر روز چیزی را انتخاب کنید که الهام‌بخش شماست',seasons:'فصل‌ها',atmospheres:'فضاها',weekdays:'روزهای هفته',months:'ماه‌های عربی',spring:'بهار',summer:'تابستان',autumn:'پاییز',winter:'زمستان',dawn:'سپیده‌دم',morning:'صبح',day:'روز',sunset:'غروب',night:'شب',chooseExperience:'تجربه Alufuq خود را انتخاب کنید',free:'رایگان',subscribeNow:'اکنون مشترک شوید',currentPlan:'طرح فعلی',aboutTitle:'درباره Alufuq',researchDisclaimer:'این برنامه مرجع دینی نیست؛ بلکه یک پروژه علمی و پژوهشی در زمینه تقویم است.',languageTitle:'زبان رابط'}),
 ku:withEnglish({settings:'ڕێکخستنەکان',checkUpdate:'پشکنینی نوێکردنەوە',subscription:'بەشداری',support:'پشتیوانی',languages:'زمانەکان',about:'دەربارە',privacy:'تایبەتمەندی',close:'داخستن',back:'گەڕانەوە',prayerTimes:'کاتی نوێژ',showAll:'هەمووی پیشان بدە',hijriCalendar:'ساڵنامەی Alufuq',gregorianCalendar:'ساڵنامەی زایینی',adhanTitle:'بانگ',adhanHint:'دەنگی بانگی دڵخواز هەڵبژێرە',previewSound:'پێشبینینی دەنگ',themes:'ثیم و پاشبنەماکان',themesHint:'هەر ڕۆژ ئەوە هەڵبژێرە کە ئیلهامت دەدات',seasons:'وەرزەکان',atmospheres:'کەشوهەوا',weekdays:'ڕۆژانی هەفتە',months:'مانگە عەرەبییەکان',spring:'بەهار',summer:'هاوین',autumn:'پاییز',winter:'زستان',dawn:'بەرەبەیان',morning:'بەیانی',day:'ڕۆژ',sunset:'خۆرئاوابوون',night:'شەو',chooseExperience:'ئەزموونی Alufuq هەڵبژێرە',free:'خۆڕایی',subscribeNow:'ئێستا بەشداربە',currentPlan:'پلانی ئێستا',aboutTitle:'دەربارەی Alufuq',researchDisclaimer:'ئەم بەرنامەیە دەسەڵاتی ئایینی نییە؛ پرۆژەیەکی زانستی و توێژینەوەیی ساڵنامەیە.',languageTitle:'زمانی ڕووکار'})
};

function resolvedLanguage(language){
 if(language!=='system')return language;
 try{return Intl.DateTimeFormat().resolvedOptions().locale||'en-US'}catch(e){return 'en-US'}
}

export function makeV3Translator(language){
 const fallback=makeTranslator(language);
 const selected=resolvedLanguage(language);
 const pack=packs[selected]||packs[selected?.split('-')[0]]||en;
 return key=>pack[key]??fallback(key)??en[key]??key;
}

export function v3LocaleTag(language){
 if(language==='system')return resolvedLanguage(language);
 return localeTag(language);
}

export function v3IsRtl(language){
 if(language==='system'){
  const base=resolvedLanguage(language).split('-')[0];
  return ['ar','fa','ur','he','ku'].includes(base);
 }
 return isRtlLocale(language);
}
