const fs=require('fs');
const assert=(ok,msg)=>{if(!ok){console.error('QA FAIL:',msg);process.exitCode=1}};
const read=p=>fs.readFileSync(p,'utf8');
const entry=read('App.js');
const app=read('src/app/AppV3.js');
const themes=read('src/app/themeCatalog.js');
const adhans=read('src/app/adhanCatalog.js');
const adhanHook=read('src/app/useAdhanAudio.js');
const gps=read('src/app/useDeviceLocation.js');
const strings=read('src/app/v3Strings.js');
const config=read('app.config.js');
const appJson=JSON.parse(read('app.json'));
const pkg=JSON.parse(read('package.json'));
const lock=JSON.parse(read('package-lock.json'));
const trial=JSON.parse(read('update-trial.json'));
const plus=JSON.parse(read('update-plus.json'));
const registry=JSON.parse(read('src/data/adhan-registry.json'));
const events=JSON.parse(read('src/data/events.json'));
const national=JSON.parse(read('src/data/national-events.json'));
const version=appJson.expo.version;
const paymentTransfer=read('src/app/PaymentTransfer.js');
const adhkarHook=read('src/app/useAdhkar.js');
const adhkarScreen=read('src/app/AdhkarScreen.js');
const adhkarWidgets=read('src/app/AdhkarWidgets.js');
const lockedRequirements=read('AL_UFUQ_LOCKED_REQUIREMENTS.md');

assert(entry.includes("import AppV3 from './src/app/AppV3'"),'App.js must use the modular V3 entry');
assert(!paymentTransfer.includes('نسخ كود الجهاز')&&!paymentTransfer.includes('Copy device code'),'device code must stay hidden from customers');
assert(paymentTransfer.includes('compactToggle')&&paymentTransfer.includes('listCard'),'Plus payment UI must stay compact/collapsible');
assert(paymentTransfer.includes('maskedLast4(CARD_NUMBER)'),'16-digit transfer number must show only the last four digits');
assert(paymentTransfer.includes('maskedLast4(ACCOUNT_NUMBER)'),'10-digit account number must show only the last four digits');
assert(!paymentTransfer.includes('style={s.number}>{ACCOUNT_NUMBER}</Text>'),'full 10-digit account number must not be rendered');
assert(lockedRequirements.includes('كود الجهاز لا يظهر للمستخدم نهائيًا'),'locked requirements file must preserve hidden device-code rule');
assert(lockedRequirements.includes('أي إصدار جديد يجب أن يحافظ على كل المتطلبات المقفلة السابقة'),'new releases must preserve prior locked requirements');
assert(paymentTransfer.includes("purpose!=='plus'||!notificationEndpoint"),'support copy must not create Plus admin requests');
assert(!paymentTransfer.includes('Alert.alert')&&!paymentTransfer.includes('كود جهازك')&&!paymentTransfer.includes('Device code copied'),'payment copy must stay silent and must never expose the device code to the customer');
assert(!app.includes("!!deviceCode&&<><Text"),'plus lock screen must not expose device code');
assert(app.includes("from './AdhkarScreen'")&&app.includes("from './AdhkarWidgets'")&&app.includes("from './useAdhkar'"),'adhkar modules must be wired into AppV3');
assert(app.includes('adhkarMorning')&&app.includes('adhkarEvening')&&app.includes('AdhkarHomeCard')&&app.includes('AdhkarSettings'),'adhkar home card, routes and settings must exist');
assert(adhkarHook.includes("now.getTime()>=fajrDate.getTime()")&&adhkarHook.includes('localMinutes<600'),'morning adhkar must begin after Fajr and expire at 10:00 AM');
assert(adhkarHook.includes('localMinutes>=1260&&localMinutes<1440'),'evening adhkar must begin at 9:00 PM and expire at midnight');
assert(adhkarHook.includes('MORNING_DONE_KEY')&&adhkarHook.includes('EVENING_DONE_KEY')&&adhkarHook.includes('markComplete'),'completed adhkar must hide for the rest of the period');
assert(adhkarScreen.includes('MORNING_ADHKAR')&&adhkarScreen.includes('EVENING_ADHKAR'),'morning and evening adhkar reading content must be bundled');
assert(adhkarWidgets.includes('setMorningAlert')&&adhkarWidgets.includes('setEveningAlert'),'morning and evening reminder switches must be independent');
assert(adhkarHook.includes("data.kind==='alofok-adhkar'")&&adhkarHook.includes('scheduleNotificationAsync'),'adhkar notifications must open the correct reading period');
assert(app.includes(`const VERSION='${version}';`),'V3 version must match app.json');
assert(pkg.version===version,'package.json version mismatch');
assert(lock.version===version&&lock.packages?.['']?.version===version,'package-lock version mismatch');
assert(trial.version===version,'Trial update manifest version mismatch');
assert(Number(String(plus.version).replace(/\./g,''))<=Number(String(version).replace(/\./g,'')),'Plus update manifest cannot point to a future unbuilt version');
assert(trial.channel==='trial'&&plus.channel==='plus','Trial and Plus update channels must stay distinct');
assert(trial.build_variant==='trial'&&plus.build_variant==='paid','manifest build variants must stay distinct');
assert(trial.package_id==='com.alofok.trial'&&plus.package_id==='com.alofok.trial','Trial and Plus must share the canonical Android package for in-place upgrade');
assert(trial.versionCode>=1000000&&trial.versionCode<2000000,'Trial manifest must stay in the Trial versionCode range');
assert(plus.versionCode>=2000000&&plus.versionCode<3000000,'Plus manifest must stay in the Plus versionCode range');
assert(trial.versionCode<plus.versionCode,'Plus versionCode must stay above Trial so Trial cannot replace Plus');
assert(trial.cross_channel_allowed===false&&plus.cross_channel_allowed===false,'cross-channel update manifests must stay disabled');
assert((config.match(/const packageId =/g)||[]).length===1,'app.config.js must contain exactly one packageId declaration');
assert(config.includes("const packageId = 'com.alofok.trial';"),'Trial and Plus must share the canonical package id');
assert(config.includes('const androidVersionCode = isPaid ? 2001119 : 1001119;'),'variant-specific Android versionCode ranges missing');
assert(config.includes("isPaid ? './assets/icon-paid.png' : './assets/icon-trial.png'"),'Trial and Plus must use their approved full launcher icons');
assert(!config.includes('adaptiveIcon'),'do not wrap full launcher artwork inside adaptiveIcon; it causes the icon to render too small');

assert(app.includes("const IS_PLUS=process.env.EXPO_PUBLIC_APP_VARIANT==='paid';"),'Plus features must be gated by paid build variant');
assert(app.includes('update-plus.json')&&app.includes('update-trial.json'),'Trial and Plus must read different update manifests');
assert(app.includes("['trial-fixed','season-spring','season-summer','season-autumn','season-winter'].includes(id)"),'trial build must allow exactly five themes: four seasons plus Mosque Minaret');
assert(app.includes("if(!IS_PLUS)return THEME_BY_ID[selectedTheme]?.image"),'trial home background must use the selected seasonal theme');
assert(app.includes('automaticThemeId(now)'),'Plus automatic theme rotation missing');
assert(app.includes("isPlus?x.id!=='trial-fixed':!x.plus"),'Plus build must expose exactly 34 themes and exclude the Trial-only minaret theme');
assert(!app.includes('THEME_ATLAS')&&!themes.includes('THEME_ATLAS'),'legacy atlas code must stay removed');
assert(!fs.existsSync('assets/themes/alofok-plus-theme-atlas-v1.jpg'),'legacy atlas file must stay deleted');
const standaloneThemeRequires=[...themes.matchAll(/require\('\.\.\/\.\.\/assets\/themes\/([^']+)'\)/g)].map(x=>x[1]);
assert(standaloneThemeRequires.length===35,'expected 35 standalone theme images including fixed trial theme');
assert(new Set(standaloneThemeRequires).size===35,'standalone theme image paths must be unique');
for(const name of standaloneThemeRequires)assert(fs.existsSync(`assets/themes/${name}`),`missing theme asset: ${name}`);

const configuredBaseSounds=(appJson.expo.plugins.find(x=>Array.isArray(x)&&x[0]==='expo-notifications')||[])[1]?.sounds||[];
assert(configuredBaseSounds.length===1&&configuredBaseSounds[0].endsWith('beautiful_adhan.wav'),'base app.json config keeps the stable fallback Adhan');
for(const name of ['beautiful_adhan.wav','adhan_andrewler.wav','adhan_aishatu98.wav','adhan_nigeria_isaac.wav','adhan_medina_ejaz215.wav','adhan_mecca_2013.wav'])assert(config.includes(`'./assets/adhan/${name}'`),`Trial notification sound missing: ${name}`);
assert(config.includes('const paidSounds = trialSounds;'),'Plus notification set must match the six restored Adhan sounds');
const playable=registry.filter(x=>x.status==='licensed'&&Array.isArray(x.available_in)&&x.available_in.length);
const trialPlayable=playable.filter(x=>x.available_in.includes('trial'));
const plusPlayable=playable.filter(x=>x.available_in.includes('paid'));
assert(playable.length===6,'expected exactly six restored approved Adhan voices');
assert(trialPlayable.length===6,'Trial must expose exactly the six restored approved Adhan voices');
for(const id of ['commons-beautiful-adhan','commons-andrewler-azan','commons-aishatu98-adhan','commons-nigeria-isaac','commons-medina-ejaz215','commons-mecca-2013'])assert(trialPlayable.some(x=>x.id===id),`restored Trial Adhan missing: ${id}`);
assert(plusPlayable.length===6,'Plus must expose exactly the same six restored Adhan voices');
for(const id of ['commons-beautiful-adhan','commons-andrewler-azan','commons-aishatu98-adhan','commons-nigeria-isaac','commons-medina-ejaz215','commons-mecca-2013'])assert(plusPlayable.some(x=>x.id===id),`restored Plus Adhan missing: ${id}`);
const rejectedIds=['commons-morocco-hassan-ii','commons-kazakhstan-shalqar','commons-aaqib-azeez','commons-mecca-maghrib-2012','commons-konya-2012','commons-tripoli-2019','commons-isfahan-shah'];
assert(!registry.some(x=>rejectedIds.includes(x.id)),'rejected Adhan ids must stay removed');
for(const id of rejectedIds)assert(!adhans.includes(`'${id}'`),`${id}: rejected Adhan must not be bundled`);
for(const x of playable){
 assert(Boolean(x.license),`${x.id}: license missing`);
 assert(Boolean(x.source),`${x.id}: source missing`);
 assert(Boolean(x.source_url),`${x.id}: source URL missing`);
 assert(Boolean(x.asset),`${x.id}: asset path missing`);
 assert(adhans.includes(`'${x.id}':require(`),`${x.id}: preview asset not bundled in adhanCatalog.js`);
 assert(adhans.includes(`'${x.id}':'`)&&adhans.includes('.wav'),`${x.id}: notification sound map missing`);
}
assert(adhanHook.includes('availableAdhanForVariant'),'Adhan hook must filter voices by Trial/Plus variant');
assert(adhanHook.includes('VARIANT_BY_ID'),'Adhan selection must be restricted to the active build variant');

assert(gps.includes('Location.Accuracy.Highest'),'GPS must request highest available accuracy');
assert(gps.includes('watchPositionAsync'),'GPS must briefly watch for a better fix');
assert(gps.includes('nearestCity'),'GPS label must support nearest seeded locality');
assert(app.includes("calculatePrayerTimes({date:civilDate,lat:location.lat,lon:location.lon"),'prayer times must use current coordinates');
assert(app.includes("method:'MWL'"),'MWL prayer calculation default missing');
assert(app.includes('schedulePrayerAlerts'),'background prayer notification scheduling missing');
assert(adhanHook.includes("const VOLUME_KEY='alofok_v3_adhan_volume';"),'Adhan volume persistence missing');
assert(adhanHook.includes('player.volume=volume'),'Adhan preview must use the selected volume');
assert(adhanHook.includes('setVolumeState(next)')&&adhanHook.includes('playerRef.current.volume=next'),'Adhan volume must update live while audio is playing');
assert(app.includes("t('adhanVolume')")&&app.includes('adhan.setVolume(level)'),'Adhan volume control UI missing');
assert(app.includes('adhan.preview(item.id)')&&app.includes('adhan.playingId===item.id'),'Adhan preview/play control must be present for every Adhan row in Trial and Plus');
assert(app.includes('adhanPreviewButton:{')&&app.includes('adhanPreviewIcon:{'),'Adhan preview button styles missing');
assert(app.includes("return <View style={[s.prayerStrip,rowDir(rtl)]}>"),'prayer strip must show all six times without horizontal scrolling');
assert(app.includes("prayerItem:{flex:1,minWidth:0,minHeight:72"),'prayer items must share the available width');

assert(strings.includes("appName:'الأفق'")&&strings.includes("appName:'al ufuq'"),'Arabic and English V3 packs are required');
assert(strings.includes("languageTitle:'Interface language'")&&strings.includes("languageTitle:'لغة الواجهة'"),'language screen strings missing');
assert(app.includes('makeV3Translator(language)'),'all V3 screens must use centralized translations');
assert(app.includes('v3IsRtl(language)'),'interface direction must follow selected language');
assert(events.every(x=>Boolean(x.en)),'all religious events need English names');
for(const rows of Object.values(national))assert(rows.every(x=>Boolean(x.name_en)),'all national events need English names');

assert(strings.includes('This app is not a religious authority')&&strings.includes('هذا البرنامج ليس دينيًا'),'research disclaimer missing');
assert(strings.includes('Nasi')&&strings.includes('شهر النسيء'),'Nasi leap-month research explanation missing');
assert(!app.includes('<View style={s.supportQuickWrap}>'),'large home support block must remain removed');
assert(!app.includes('<View style={[s.dualCards,rowDir(rtl)]}>'),'mini calendar summary cards must stay removed');
assert(app.includes("import religiousEvents from '../data/events.json';")&&app.includes("import nationalEvents from '../data/national-events.json';"),'calendar event data must be wired into the app');
assert(app.includes('info.month===todayInfo.month&&info.year===todayInfo.year'),'Hijri today highlight must match day, month, and year');
assert(app.includes('country={location.country}'),'Gregorian national events must follow the selected/current country');
assert(app.includes('religiousEventsFor(info.month,day)'),'Hijri religious events must be enabled');
assert(app.includes("import {useCountryHolidays} from './useCountryHolidays';"),'global country holiday hook must be wired into calendar');
assert(app.includes('useCountryHolidays(country,year)'),'Gregorian calendar must load holidays for GPS country and visible year');
assert(app.includes("import religiousEventsExtra from '../data/religious-events-extra.json';"),'expanded religious event data must be wired into Hijri calendar');
const holidayHook=read('src/app/useCountryHolidays.js');
assert(holidayHook.includes('https://nagerholidays.com/api/v4/Holidays'),'global holiday API must remain configured');
assert(holidayHook.includes('AsyncStorage'),'country holidays must be cached for offline fallback');
assert(holidayHook.includes("code==='IQ'&&String(x.date).slice(5)==='03-16'"),'Iraq March 16 political observance must be filtered from remote holiday data');
const iraq=JSON.parse(read('src/data/iraq-observances.json'));
for(const key of ['عيد الجيش العراقي','عيد الشرطة العراقية','عيد نوروز','اليوم الوطني العراقي','يوم النصر على داعش'])assert(iraq.some(x=>x.name_ar===key),`Iraq observance missing: ${key}`);
assert(!iraq.some(x=>String(x.name_ar||'').includes('البعث')||String(x.name_en||'').toLowerCase().includes("ba'ath")),'political Baath-era commemoration must stay excluded from Iraq observances');

// Legal, privacy and authenticity verification guards
assert(app.includes("from './LegalScreens';"),'legal/authenticity screens must be wired');
assert(app.includes("screen==='copyright'")&&app.includes("screen==='authenticity'"),'copyright and authenticity routes must exist');
const legal=read('src/app/LegalScreens.js');
assert(legal.includes('سياسة الخصوصية')&&legal.includes('حقوق الطبع والنشر'),'full Arabic privacy and copyright screens required');
assert(legal.includes('وسام محمد')&&legal.includes('Wissam Digital'),'owner identity must appear in privacy/copyright screens');
const activation=read('src/app/TrialPlusActivation.js');
assert(app.includes("from './TrialPlusActivation';"),'Trial Plus activation screen must be wired');
assert(activation.includes('payment_data_copied')&&activation.includes('EXPO_PUBLIC_PAYMENT_COPY_WEBHOOK'),'copy-payment event must be ready for secure admin notification');
assert(activation.includes("const inIraq=country==='IQ'"),'Plus activation must be restricted to Iraq');
assert(legal.includes('react-native-qrcode-svg'),'authenticity screen must render QR codes');
const authClient=read('src/app/authenticityClient.js');
assert(authClient.includes('EXPO_PUBLIC_AUTH_API_URL')&&authClient.includes('/v1/authenticity/challenge'),'authenticity API contract missing');
assert(authClient.includes("edition,version,installationId"),'authenticity challenge must bind edition, version and installation');
const pkgLegal=JSON.parse(read('package.json'));
assert(pkgLegal.dependencies['react-native-qrcode-svg']&&pkgLegal.dependencies['react-native-svg'],'QR dependencies must be installed');


// Device-bound Plus protection guards
const deviceSecurity=read('src/services/deviceSecurity.js');
const apkUpdater=read('src/services/apkUpdater.js');
assert(pkg.dependencies['expo-secure-store']&&pkg.dependencies['expo-crypto']&&pkg.dependencies['tweetnacl'],'device-bound encryption dependencies must be installed');
assert(deviceSecurity.includes('SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY'),'device secret must be kept in device-only secure storage');
assert(deviceSecurity.includes('nacl.secretbox'),'Plus payload must use authenticated encryption');
assert(deviceSecurity.includes('/api/plus/status')&&deviceSecurity.includes('/api/plus/payload'),'Plus approval and protected payload API endpoints missing');
assert(app.includes('unlockPlusForThisDevice')&&app.includes("plusAccess!=='unlocked'"),'Plus build must stay locked until this device is approved');
assert(app.includes('prepareEncryptedPlusBundle'),'approved Trial must prepare the encrypted Plus payload before upgrade');
assert(app.includes('downloadAndInstallApk'),'updates must install directly from inside the Android app');
assert(apkUpdater.includes('android.intent.action.VIEW'),'APK installer intent missing');
assert(fs.existsSync('plus-entitlements.json')&&fs.existsSync('plus-bundle.json'),'protected Plus registry/payload files missing');

// Trial advertising guards
const trialAds=read('src/app/TrialAds.js');
assert(app.includes("from './TrialAds';"),'trial advertising client must be wired into V3');
assert(app.includes('useTrialAd({enabled:!IS_PLUS'),'ads must be disabled in Plus at the app boundary');
assert(app.includes("...(!IS_PLUS?[['▣','advertise','advertise']]:[])"),'Advertise menu entry must exist only in Trial');
assert(trialAds.includes('MAX_WEEKLY_ADS=1'),'Trial must cap advertising at one impression per week');
assert(trialAds.includes('/v1/ads/approved/next'),'users must fetch only approved ads');
assert(trialAds.includes("item.status!=='approved'"),'client must reject any ad that is not approved');
assert(trialAds.includes('/v1/ads/submissions'),'advertisers need a moderated submission endpoint');
assert(trialAds.includes("status:'pending_review'"),'new ad submissions must remain pending until manual approval');
assert(trialAds.includes('EXPO_PUBLIC_AD_PAYMENT_URL'),'ad payment must use configurable provider routing, never a hardcoded card number');

if(process.exitCode)process.exit(process.exitCode);
console.log('Release QA passed for Al-Ufuq V3',version);
